version: "3.1"

services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
